In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV, train_test_split

In [2]:
df1=pd.read_csv('C:/Users/student/Desktop/CT.csv')

In [3]:
df1=df1[df1['VISCODE']!='m24']
df1

,RID,VISCODE,CDRSB,ADAS11,ADAS13,MMSE,RAVLT_immediate,RAVLT_learning,RAVLT_forgetting,RAVLT_perc_forgetting,...,EcogPtDivatt,EcogPtTotal,EcogSPMem,EcogSPLang,EcogSPVisspat,EcogSPPlan,EcogSPOrgan,EcogSPDivatt,EcogSPTotal,DX
0,3,bl,4.5,22.00,31.00,20,22.0,1.0,4.0,100.0000,...,1.816072,1.672832,2.143618,1.716137,1.603997,1.717245,1.793346,1.987487,1.829041,AD
1,3,m06,6.0,19.00,30.00,24,19.0,2.0,6.0,100.0000,...,1.816072,1.672832,2.143618,1.716137,1.603997,1.717245,1.793346,1.987487,1.829041,AD
2,3,m12,3.5,24.00,35.00,17,31.0,2.0,7.0,100.0000,...,1.816072,1.672832,2.143618,1.716137,1.603997,1.717245,1.793346,1.987487,1.829041,AD
3,3,m18,3.5,24.00,35.00,17,31.0,2.0,7.0,100.0000,...,1.816072,1.672832,2.143618,1.716137,1.603997,1.717245,1.793346,1.987487,1.829041,AD
5,5,bl,0.0,8.67,14.67,29,37.0,4.0,4.0,44.4444,...,1.816072,1.672832,2.143618,1.716137,1.603997,1.717245,1.793346,1.987487,1.829041,CN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5698,5004,m18,3.0,11.00,14.00,30,43.0,8.0,5.0,45.4545,...,1.000000,1.054050,3.125000,2.555560,3.000000,2.400000,2.166670,2.500000,2.666670,MCI
5700,5106,bl,4.0,30.00,42.00,20,18.0,2.0,4.0,100.0000,...,1.250000,1.257140,3.125000,1.777780,2.428570,2.400000,3.000000,3.000000,2.564100,AD
5701,5106,m06,6.0,26.00,38.00,17,12.0,2.0,3.0,100.0000,...,1.000000,1.270270,2.875000,1.444440,2.000000,2.200000,2.833330,2.750000,2.282050,AD
5702,5106,m12,6.0,26.00,38.00,17,12.0,2.0,3.0,100.0000,...,1.000000,1.270270,2.875000,1.444440,2.000000,2.200000,2.833330,2.750000,2.282050,AD
5703,5106,m18,6.0,26.00,38.00,17,12.0,2.0,3.0,100.0000,...,1.000000,1.270270,2.875000,1.444440,2.000000,2.200000,2.833330,2.750000,2.282050,AD

In [4]:
df1['DX']=df1['DX'].map({'AD':0, 'MCI':1, 'CN':2})

In [5]:
#df.fillna(0,inplace=True)
x=df1.iloc[:,2:-1] ## independent features
y=df1.iloc[:,-1] ## dependent features

In [6]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size = 0.30,random_state=42)

In [7]:
pipeline=Pipeline([
    ('scaler', StandardScaler()),
    ('model', Lasso())              
])

In [8]:
search=GridSearchCV(pipeline,
                  {'model__alpha':np.arange(0.1,3,0.1)},
                   cv=5,
                   scoring='neg_mean_squared_error',
                   verbose=3
                  )

In [9]:
search.fit(x_train,y_train)

Fitting 5 folds for each of 29 candidates, totalling 145 fits
[CV 1/5] END .................model__alpha=0.1;, score=-0.185 total time=   0.0s
[CV 2/5] END .................model__alpha=0.1;, score=-0.173 total time=   0.0s
[CV 3/5] END .................model__alpha=0.1;, score=-0.202 total time=   0.0s
[CV 4/5] END .................model__alpha=0.1;, score=-0.184 total time=   0.0s
[CV 5/5] END .................model__alpha=0.1;, score=-0.181 total time=   0.0s
[CV 1/5] END .................model__alpha=0.2;, score=-0.214 total time=   0.0s
[CV 2/5] END .................model__alpha=0.2;, score=-0.213 total time=   0.0s
[CV 3/5] END .................model__alpha=0.2;, score=-0.246 total time=   0.0s
[CV 4/5] END .................model__alpha=0.2;, score=-0.226 total time=   0.0s
[CV 5/5] END .................model__alpha=0.2;, score=-0.221 total time=   0.0s
[CV 1/5] END .model__alpha=0.30000000000000004;, score=-0.262 total time=   0.0s
[CV 2/5] END .model__alpha=0.30000000000000004;, score=-0.268 total time=   0.0s
[CV 3/5] END .model__alpha=0.30000000000000004;, score=-0.309 total time=   0.0s
[CV 4/5] END .model__alpha=0.30000000000000004;, score=-0.284 total time=   0.0s
[CV 5/5] END .model__alpha=0.30000000000000004;, score=-0.280 total time=   0.0s
[CV 1/5] END .................model__alpha=0.4;, score=-0.327 total time=   0.0s
[CV 2/5] END .................model__alpha=0.4;, score=-0.339 total time=   0.0s
[CV 3/5] END .................model__alpha=0.4;, score=-0.383 total time=   0.0s
[CV 4/5] END .................model__alpha=0.4;, score=-0.356 total time=   0.0s
[CV 5/5] END .................model__alpha=0.4;, score=-0.359 total time=   0.0s
[CV 1/5] END .................model__alpha=0.5;, score=-0.411 total time=   0.0s
[CV 2/5] END .................model__alpha=0.5;, score=-0.424 total time=   0.0s
[CV 3/5] END .................model__alpha=0.5;, score=-0.475 total time=   0.0s
[CV 4/5] END .................model__alpha=0.5;, score=-0.448 total time=   0.0s
[CV 5/5] END .................model__alpha=0.5;, score=-0.457 total time=   0.0s
[CV 1/5] END .................model__alpha=0.6;, score=-0.469 total time=   0.0s
[CV 2/5] END .................model__alpha=0.6;, score=-0.473 total time=   0.0s
[CV 3/5] END .................model__alpha=0.6;, score=-0.525 total time=   0.0s
[CV 4/5] END .................model__alpha=0.6;, score=-0.501 total time=   0.0s
[CV 5/5] END .................model__alpha=0.6;, score=-0.509 total time=   0.0s
[CV 1/5] END ..model__alpha=0.7000000000000001;, score=-0.469 total time=   0.0s
[CV 2/5] END ..model__alpha=0.7000000000000001;, score=-0.473 total time=   0.0s
[CV 3/5] END ..model__alpha=0.7000000000000001;, score=-0.525 total time=   0.0s
[CV 4/5] END ..model__alpha=0.7000000000000001;, score=-0.501 total time=   0.0s
[CV 5/5] END ..model__alpha=0.7000000000000001;, score=-0.509 total time=   0.0s
[CV 1/5] END .................model__alpha=0.8;, score=-0.469 total time=   0.0s
[CV 2/5] END .................model__alpha=0.8;, score=-0.473 total time=   0.0s
[CV 3/5] END .................model__alpha=0.8;, score=-0.525 total time=   0.0s
[CV 4/5] END .................model__alpha=0.8;, score=-0.501 total time=   0.0s
[CV 5/5] END .................model__alpha=0.8;, score=-0.509 total time=   0.0s
[CV 1/5] END .................model__alpha=0.9;, score=-0.469 total time=   0.0s
[CV 2/5] END .................model__alpha=0.9;, score=-0.473 total time=   0.0s
[CV 3/5] END .................model__alpha=0.9;, score=-0.525 total time=   0.0s
[CV 4/5] END .................model__alpha=0.9;, score=-0.501 total time=   0.0s
[CV 5/5] END .................model__alpha=0.9;, score=-0.509 total time=   0.0s
[CV 1/5] END .................model__alpha=1.0;, score=-0.469 total time=   0.0s
[CV 2/5] END .................model__alpha=1.0;, score=-0.473 total time=   0.0s
[CV 3/5] END .................model__alpha=1.0;, score=-0.525 total time=   0.0s
[CV 4/5] END .................model__alpha=1.0;, score=-0.501 total time=   0.0s
[CV 5/5] END .................model__alpha=1.0;, score=-0.509 total time=   0.0s
[CV 1/5] END .................model__alpha=1.1;, score=-0.469 total time=   0.0s
[CV 2/5] END .................model__alpha=1.1;, score=-0.473 total time=   0.0s
[CV 3/5] END .................model__alpha=1.1;, score=-0.525 total time=   0.0s
[CV 4/5] END .................model__alpha=1.1;, score=-0.501 total time=   0.0s
[CV 5/5] END .................model__alpha=1.1;, score=-0.509 total time=   0.0s
[CV 1/5] END ..model__alpha=1.2000000000000002;, score=-0.469 total time=   0.0s
[CV 2/5] END ..model__alpha=1.2000000000000002;, score=-0.473 total time=   0.0s
[CV 3/5] END ..model__alpha=1.2000000000000002;, score=-0.525 total time=   0.0s
[CV 4/5] END ..model__alpha=1.2000000000000002;, score=-0.501 total time=   0.0s
[CV 5/5] END ..model__alpha=1.2000000000000002;, score=-0.509 total time=   0.0s
[CV 1/5] END ..model__alpha=1.3000000000000003;, score=-0.469 total time=   0.0s
[CV 2/5] END ..model__alpha=1.3000000000000003;, score=-0.473 total time=   0.0s
[CV 3/5] END ..model__alpha=1.3000000000000003;, score=-0.525 total time=   0.0s
[CV 4/5] END ..model__alpha=1.3000000000000003;, score=-0.501 total time=   0.0s
[CV 5/5] END ..model__alpha=1.3000000000000003;, score=-0.509 total time=   0.0s
[CV 1/5] END ..model__alpha=1.4000000000000001;, score=-0.469 total time=   0.0s
[CV 2/5] END ..model__alpha=1.4000000000000001;, score=-0.473 total time=   0.0s
[CV 3/5] END ..model__alpha=1.4000000000000001;, score=-0.525 total time=   0.0s
[CV 4/5] END ..model__alpha=1.4000000000000001;, score=-0.501 total time=   0.0s
[CV 5/5] END ..model__alpha=1.4000000000000001;, score=-0.509 total time=   0.0s
[CV 1/5] END ..model__alpha=1.5000000000000002;, score=-0.469 total time=   0.0s
[CV 2/5] END ..model__alpha=1.5000000000000002;, score=-0.473 total time=   0.0s
[CV 3/5] END ..model__alpha=1.5000000000000002;, score=-0.525 total time=   0.0s
[CV 4/5] END ..model__alpha=1.5000000000000002;, score=-0.501 total time=   0.0s
[CV 5/5] END ..model__alpha=1.5000000000000002;, score=-0.509 total time=   0.0s
[CV 1/5] END .................model__alpha=1.6;, score=-0.469 total time=   0.0s
[CV 2/5] END .................model__alpha=1.6;, score=-0.473 total time=   0.0s
[CV 3/5] END .................model__alpha=1.6;, score=-0.525 total time=   0.0s
[CV 4/5] END .................model__alpha=1.6;, score=-0.501 total time=   0.0s
[CV 5/5] END .................model__alpha=1.6;, score=-0.509 total time=   0.0s
[CV 1/5] END ..model__alpha=1.7000000000000002;, score=-0.469 total time=   0.0s
[CV 2/5] END ..model__alpha=1.7000000000000002;, score=-0.473 total time=   0.0s
[CV 3/5] END ..model__alpha=1.7000000000000002;, score=-0.525 total time=   0.0s
[CV 4/5] END ..model__alpha=1.7000000000000002;, score=-0.501 total time=   0.0s
[CV 5/5] END ..model__alpha=1.7000000000000002;, score=-0.509 total time=   0.0s
[CV 1/5] END ..model__alpha=1.8000000000000003;, score=-0.469 total time=   0.0s
[CV 2/5] END ..model__alpha=1.8000000000000003;, score=-0.473 total time=   0.0s
[CV 3/5] END ..model__alpha=1.8000000000000003;, score=-0.525 total time=   0.0s
[CV 4/5] END ..model__alpha=1.8000000000000003;, score=-0.501 total time=   0.0s
[CV 5/5] END ..model__alpha=1.8000000000000003;, score=-0.509 total time=   0.0s
[CV 1/5] END ..model__alpha=1.9000000000000001;, score=-0.469 total time=   0.0s
[CV 2/5] END ..model__alpha=1.9000000000000001;, score=-0.473 total time=   0.0s
[CV 3/5] END ..model__alpha=1.9000000000000001;, score=-0.525 total time=   0.0s
[CV 4/5] END ..model__alpha=1.9000000000000001;, score=-0.501 total time=   0.0s
[CV 5/5] END ..model__alpha=1.9000000000000001;, score=-0.509 total time=   0.0s
[CV 1/5] END .................model__alpha=2.0;, score=-0.469 total time=   0.0s
[CV 2/5] END .................model__alpha=2.0;, score=-0.473 total time=   0.0s
[CV 3/5] END .................model__alpha=2.0;, score=-0.525 total time=   0.0s
[CV 4/5] END .................model__alpha=2.0;, score=-0.501 total time=   0.0s
[CV 5/5] END .................model__alpha=2.0;, score=-0.509 total time=   0.0s
[CV 1/5] END .................model__alpha=2.1;, score=-0.469 total time=   0.0s
[CV 2/5] END .................model__alpha=2.1;, score=-0.473 total time=   0.0s
[CV 3/5] END .................model__alpha=2.1;, score=-0.525 total time=   0.0s
[CV 4/5] END .................model__alpha=2.1;, score=-0.501 total time=   0.0s
[CV 5/5] END .................model__alpha=2.1;, score=-0.509 total time=   0.0s
[CV 1/5] END .................model__alpha=2.2;, score=-0.469 total time=   0.0s
[CV 2/5] END .................model__alpha=2.2;, score=-0.473 total time=   0.0s
[CV 3/5] END .................model__alpha=2.2;, score=-0.525 total time=   0.0s
[CV 4/5] END .................model__alpha=2.2;, score=-0.501 total time=   0.0s
[CV 5/5] END .................model__alpha=2.2;, score=-0.509 total time=   0.0s
[CV 1/5] END ..model__alpha=2.3000000000000003;, score=-0.469 total time=   0.0s
[CV 2/5] END ..model__alpha=2.3000000000000003;, score=-0.473 total time=   0.0s
[CV 3/5] END ..model__alpha=2.3000000000000003;, score=-0.525 total time=   0.0s
[CV 4/5] END ..model__alpha=2.3000000000000003;, score=-0.501 total time=   0.0s
[CV 5/5] END ..model__alpha=2.3000000000000003;, score=-0.509 total time=   0.0s
[CV 1/5] END ..model__alpha=2.4000000000000004;, score=-0.469 total time=   0.0s
[CV 2/5] END ..model__alpha=2.4000000000000004;, score=-0.473 total time=   0.0s
[CV 3/5] END ..model__alpha=2.4000000000000004;, score=-0.525 total time=   0.0s
[CV 4/5] END ..model__alpha=2.4000000000000004;, score=-0.501 total time=   0.0s
[CV 5/5] END ..model__alpha=2.4000000000000004;, score=-0.509 total time=   0.0s
[CV 1/5] END ..model__alpha=2.5000000000000004;, score=-0.469 total time=   0.0s
[CV 2/5] END ..model__alpha=2.5000000000000004;, score=-0.473 total time=   0.0s
[CV 3/5] END ..model__alpha=2.5000000000000004;, score=-0.525 total time=   0.0s
[CV 4/5] END ..model__alpha=2.5000000000000004;, score=-0.501 total time=   0.0s
[CV 5/5] END ..model__alpha=2.5000000000000004;, score=-0.509 total time=   0.0s
[CV 1/5] END .................model__alpha=2.6;, score=-0.469 total time=   0.0s
[CV 2/5] END .................model__alpha=2.6;, score=-0.473 total time=   0.0s
[CV 3/5] END .................model__alpha=2.6;, score=-0.525 total time=   0.0s
[CV 4/5] END .................model__alpha=2.6;, score=-0.501 total time=   0.0s
[CV 5/5] END .................model__alpha=2.6;, score=-0.509 total time=   0.0s
[CV 1/5] END .................model__alpha=2.7;, score=-0.469 total time=   0.0s
[CV 2/5] END .................model__alpha=2.7;, score=-0.473 total time=   0.0s
[CV 3/5] END .................model__alpha=2.7;, score=-0.525 total time=   0.0s
[CV 4/5] END .................model__alpha=2.7;, score=-0.501 total time=   0.0s
[CV 5/5] END .................model__alpha=2.7;, score=-0.509 total time=   0.0s
[CV 1/5] END ..model__alpha=2.8000000000000003;, score=-0.469 total time=   0.0s
[CV 2/5] END ..model__alpha=2.8000000000000003;, score=-0.473 total time=   0.0s
[CV 3/5] END ..model__alpha=2.8000000000000003;, score=-0.525 total time=   0.0s
[CV 4/5] END ..model__alpha=2.8000000000000003;, score=-0.501 total time=   0.0s
[CV 5/5] END ..model__alpha=2.8000000000000003;, score=-0.509 total time=   0.0s
[CV 1/5] END ..model__alpha=2.9000000000000004;, score=-0.469 total time=   0.0s
[CV 2/5] END ..model__alpha=2.9000000000000004;, score=-0.473 total time=   0.0s
[CV 3/5] END ..model__alpha=2.9000000000000004;, score=-0.525 total time=   0.0s
[CV 4/5] END ..model__alpha=2.9000000000000004;, score=-0.501 total time=   0.0s
[CV 5/5] END ..model__alpha=2.9000000000000004;, score=-0.509 total time=   0.0s

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model', Lasso())]),
             param_grid={'model__alpha': array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3,
       1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6,
       2.7, 2.8, 2.9])},
             scoring='neg_mean_squared_error', verbose=3)

In [10]:
search.best_params_

{'model__alpha': 0.1}

In [11]:
from sklearn.linear_model import Lasso
 
lasso = Lasso(alpha = [0.03])
lasso.fit(x_train, y_train)
y_pred1 = lasso.predict(x_test)
 
            
lasso_coeff = pd.DataFrame()
lasso_coeff["Columns"] = x_train.columns
lasso_coeff['Coefficient'] = pd.Series(lasso.coef_)
print(lasso_coeff)

                  Columns  Coefficient
0                   CDRSB    -0.150351
1                  ADAS11     0.017364
2                  ADAS13    -0.019261
3                    MMSE     0.009257
4         RAVLT_immediate     0.004995
5          RAVLT_learning     0.008057
6        RAVLT_forgetting    -0.000000
7   RAVLT_perc_forgetting    -0.001881
8                     FAQ    -0.011414
9                    MOCA    -0.000000
10              EcogPtMem    -0.012086
11             EcogPtLang    -0.000000
12          EcogPtVisspat    -0.000000
13             EcogPtPlan    -0.000000
14            EcogPtOrgan    -0.000000
15           EcogPtDivatt    -0.000000
16            EcogPtTotal    -0.000000
17              EcogSPMem    -0.000000
18             EcogSPLang    -0.000000
19          EcogSPVisspat     0.000000
20             EcogSPPlan    -0.000000
21            EcogSPOrgan    -0.000000
22           EcogSPDivatt    -0.000000
23            EcogSPTotal    -0.000000

In [12]:
lasso_coeff.to_csv('CTlasso.csv', index=True)

# MRI

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV, train_test_split

In [2]:
df2=pd.read_csv('C:/Users/Maninder/Desktop/ARIMA.csv')

In [3]:
df2=df2[df2['VISCODE']!='m24']
df2

,RID,VISCODE,ST101SV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST102CV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST102SA_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST102TA_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST102TS_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST103CV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST103SA_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST103TA_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,...,ST97TS_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST98CV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST98SA_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST98TA_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST98TS_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST99CV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST99SA_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST99TA_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST99TS_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST9SV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16
0,3,bl,1692.0,3539.0,1579.0,2.121,0.645,1881.0,697.0,2.214,...,0.591,3681.0,1734.0,1.942,0.696,10387.0,3316.0,2.545,0.686,3304.0
1,3,m06,1394.0,3474.0,1647.0,2.028,0.580,1994.0,756.0,2.177,...,0.598,4060.0,1868.0,2.051,0.723,9311.0,3138.0,2.445,0.713,3173.0
2,3,m12,1521.0,3234.0,1573.0,2.011,0.627,1776.0,712.0,2.046,...,0.563,3921.0,1898.0,1.969,0.739,9736.0,3240.0,2.502,0.685,3235.0
3,3,m18,1521.0,3234.0,1573.0,2.011,0.627,1776.0,712.0,2.046,...,0.563,3921.0,1898.0,1.969,0.739,9736.0,3240.0,2.502,0.685,3235.0
5,5,bl,1578.0,2862.0,1312.0,2.065,0.609,2305.0,763.0,2.650,...,0.628,5180.0,1868.0,2.543,0.709,11579.0,3387.0,2.911,0.660,1623.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5698,5004,m18,1612.0,3957.0,1432.0,2.542,0.660,2136.0,728.0,2.703,...,0.639,5122.0,1978.0,2.249,0.662,10428.0,3036.0,2.964,0.708,1933.0
5700,5106,bl,1340.0,3544.0,1607.0,2.059,0.543,1419.0,687.0,1.872,...,0.509,4503.0,2129.0,1.993,0.662,9280.0,3127.0,2.564,0.660,1789.0
5701,5106,m06,1340.0,3544.0,1607.0,2.059,0.543,1419.0,687.0,1.872,...,0.509,4503.0,2129.0,1.993,0.662,9280.0,3127.0,2.564,0.660,1789.0
5702,5106,m12,1340.0,3544.0,1607.0,2.059,0.543,1419.0,687.0,1.872,...,0.509,4503.0,2129.0,1.993,0.662,9280.0,3127.0,2.564,0.660,1789.0
5703,5106,m18,1340.0,3544.0,1607.0,2.059,0.543,1419.0,687.0,1.872,...,0.509,4503.0,2129.0,1.993,0.662,9280.0,3127.0,2.564,0.660,1789.0

In [77]:
df2['DX']=df2['DX'].map({'AD':0, 'MCI':1, 'CN':2})

In [4]:
#df.fillna(0,inplace=True)
x=df2.iloc[:,2:-1] ## independent features
y=df2.iloc[:,-1] ## dependent features

In [5]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size = 0.30,random_state=42)

In [6]:
x_train

,ST101SV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST102CV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST102SA_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST102TA_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST102TS_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST103CV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST103SA_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST103TA_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST103TS_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST104CV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,...,ST97TA_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST97TS_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST98CV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST98SA_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST98TA_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST98TS_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST99CV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST99SA_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST99TA_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,ST99TS_UCSFFSX_11_02_15_UCSFFSX51_08_01_16
5008,1418.0,4008.0,1552.0,2.294,0.719,1020.0,329.0,2.299,0.553,3125.0,...,2.221,0.835,4284.0,1457.0,2.351,0.944,10619.0,3302.0,2.636,0.856
3315,1340.0,4126.0,1675.0,2.315,0.581,2005.0,564.0,3.102,1.004,3416.0,...,1.810,0.643,4751.0,1790.0,2.456,0.859,12170.0,2978.0,3.280,0.793
5563,1446.0,4694.0,1695.0,2.502,0.511,2279.0,792.0,2.473,0.827,3744.0,...,1.965,0.619,4617.0,1792.0,2.211,0.775,11047.0,3272.0,2.767,0.683
4507,1407.0,4160.0,1498.0,2.604,0.732,2355.0,611.0,3.170,0.746,3008.0,...,2.258,0.629,4614.0,1741.0,2.341,0.757,11247.0,3160.0,2.915,0.606
1953,1453.0,2993.0,1158.0,2.370,0.750,1794.0,559.0,2.695,0.954,3717.0,...,2.038,0.721,3903.0,1327.0,2.512,0.787,9808.0,3123.0,2.633,0.775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5532,1425.0,3670.0,1681.0,2.066,0.548,1802.0,584.0,2.637,0.618,4547.0,...,1.858,0.647,4446.0,1668.0,2.426,0.637,9938.0,3095.0,2.753,0.584
582,1411.0,2845.0,1441.0,1.968,0.616,2221.0,747.0,2.554,0.823,3750.0,...,1.874,0.606,4331.0,1734.0,2.353,0.655,11979.0,3782.0,2.620,0.818
3865,1910.0,4058.0,1644.0,2.320,0.539,1898.0,899.0,1.902,0.660,4982.0,...,1.763,0.535,5760.0,2311.0,2.158,0.773,10311.0,3984.0,2.122,0.681
4715,1556.0,2891.0,1123.0,2.349,0.693,2582.0,661.0,3.132,0.965,3338.0,...,2.039,0.686,5539.0,2101.0,2.204,0.797,12154.0,3483.0,2.719,0.847
1075,1167.0,3491.0,1623.0,2.105,0.594,1575.0,622.0,2.115,0.762,3327.0,...,1.899,0.636,3145.0,1493.0,2.061,0.752,8273.0,2771.0,2.627,0.752

In [7]:
pipeline=Pipeline([
    ('scaler', StandardScaler()),
    ('model', Lasso())              
])

In [8]:
search=GridSearchCV(pipeline,
                  {'model__alpha':np.arange(0.1,3,0.1)},
                   cv=5,
                   scoring='neg_mean_squared_error',
                   verbose=3
                  )

In [9]:
search.fit(x_train,y_train)

Fitting 5 folds for each of 29 candidates, totalling 145 fits

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.693e+06, tolerance: 1.172e+05
  model = cd_fast.enet_coordinate_descent(

[CV 1/5] END ............model__alpha=0.1;, score=-333604.852 total time=   1.7s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.404e+06, tolerance: 1.191e+05
  model = cd_fast.enet_coordinate_descent(

[CV 2/5] END ............model__alpha=0.1;, score=-318450.293 total time=   0.3s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.557e+06, tolerance: 1.189e+05
  model = cd_fast.enet_coordinate_descent(

[CV 3/5] END ............model__alpha=0.1;, score=-313803.819 total time=   0.3s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.914e+06, tolerance: 1.220e+05
  model = cd_fast.enet_coordinate_descent(

[CV 4/5] END ............model__alpha=0.1;, score=-277533.261 total time=   0.4s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.359e+06, tolerance: 1.208e+05
  model = cd_fast.enet_coordinate_descent(

[CV 5/5] END ............model__alpha=0.1;, score=-312274.921 total time=   0.4s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.186e+05, tolerance: 1.172e+05
  model = cd_fast.enet_coordinate_descent(

[CV 1/5] END ............model__alpha=0.2;, score=-330851.450 total time=   0.4s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.680e+05, tolerance: 1.191e+05
  model = cd_fast.enet_coordinate_descent(

[CV 2/5] END ............model__alpha=0.2;, score=-316954.920 total time=   0.3s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.284e+05, tolerance: 1.189e+05
  model = cd_fast.enet_coordinate_descent(

[CV 3/5] END ............model__alpha=0.2;, score=-312297.129 total time=   0.3s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.239e+05, tolerance: 1.220e+05
  model = cd_fast.enet_coordinate_descent(

[CV 4/5] END ............model__alpha=0.2;, score=-276847.752 total time=   0.4s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.189e+06, tolerance: 1.208e+05
  model = cd_fast.enet_coordinate_descent(

[CV 5/5] END ............model__alpha=0.2;, score=-310786.198 total time=   0.4s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.251e+05, tolerance: 1.172e+05
  model = cd_fast.enet_coordinate_descent(

[CV 1/5] END model__alpha=0.30000000000000004;, score=-328868.528 total time=   0.4s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.027e+05, tolerance: 1.191e+05
  model = cd_fast.enet_coordinate_descent(

[CV 2/5] END model__alpha=0.30000000000000004;, score=-315864.239 total time=   0.3s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.261e+05, tolerance: 1.189e+05
  model = cd_fast.enet_coordinate_descent(

[CV 3/5] END model__alpha=0.30000000000000004;, score=-311332.264 total time=   0.3s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.947e+05, tolerance: 1.220e+05
  model = cd_fast.enet_coordinate_descent(

[CV 4/5] END model__alpha=0.30000000000000004;, score=-276629.097 total time=   0.3s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.725e+05, tolerance: 1.208e+05
  model = cd_fast.enet_coordinate_descent(

[CV 5/5] END model__alpha=0.30000000000000004;, score=-310144.431 total time=   0.3s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.786e+05, tolerance: 1.172e+05
  model = cd_fast.enet_coordinate_descent(

[CV 1/5] END ............model__alpha=0.4;, score=-327459.347 total time=   0.4s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.492e+05, tolerance: 1.191e+05
  model = cd_fast.enet_coordinate_descent(

[CV 2/5] END ............model__alpha=0.4;, score=-315070.257 total time=   0.4s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.655e+05, tolerance: 1.189e+05
  model = cd_fast.enet_coordinate_descent(

[CV 3/5] END ............model__alpha=0.4;, score=-310588.306 total time=   0.4s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.500e+05, tolerance: 1.220e+05
  model = cd_fast.enet_coordinate_descent(

[CV 4/5] END ............model__alpha=0.4;, score=-276609.891 total time=   0.4s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.021e+05, tolerance: 1.208e+05
  model = cd_fast.enet_coordinate_descent(

[CV 5/5] END ............model__alpha=0.4;, score=-310043.404 total time=   0.4s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.870e+05, tolerance: 1.172e+05
  model = cd_fast.enet_coordinate_descent(

[CV 1/5] END ............model__alpha=0.5;, score=-326039.994 total time=   0.3s
[CV 2/5] END ............model__alpha=0.5;, score=-314552.987 total time=   0.3s
[CV 3/5] END ............model__alpha=0.5;, score=-310312.597 total time=   0.3s
[CV 4/5] END ............model__alpha=0.5;, score=-276456.312 total time=   0.3s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.983e+05, tolerance: 1.208e+05
  model = cd_fast.enet_coordinate_descent(

[CV 5/5] END ............model__alpha=0.5;, score=-310269.767 total time=   0.3s
[CV 1/5] END ............model__alpha=0.6;, score=-324570.100 total time=   0.2s
[CV 2/5] END ............model__alpha=0.6;, score=-313883.173 total time=   0.3s
[CV 3/5] END ............model__alpha=0.6;, score=-310361.935 total time=   0.2s
[CV 4/5] END ............model__alpha=0.6;, score=-276398.953 total time=   0.3s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.839e+05, tolerance: 1.208e+05
  model = cd_fast.enet_coordinate_descent(

[CV 5/5] END ............model__alpha=0.6;, score=-310655.760 total time=   0.3s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.925e+05, tolerance: 1.172e+05
  model = cd_fast.enet_coordinate_descent(

[CV 1/5] END model__alpha=0.7000000000000001;, score=-323352.354 total time=   0.3s
[CV 2/5] END model__alpha=0.7000000000000001;, score=-313184.233 total time=   0.2s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.374e+05, tolerance: 1.189e+05
  model = cd_fast.enet_coordinate_descent(

[CV 3/5] END model__alpha=0.7000000000000001;, score=-310387.388 total time=   0.3s
[CV 4/5] END model__alpha=0.7000000000000001;, score=-276597.208 total time=   0.2s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.464e+05, tolerance: 1.208e+05
  model = cd_fast.enet_coordinate_descent(

[CV 5/5] END model__alpha=0.7000000000000001;, score=-310944.417 total time=   0.3s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.169e+06, tolerance: 1.172e+05
  model = cd_fast.enet_coordinate_descent(

[CV 1/5] END ............model__alpha=0.8;, score=-322276.249 total time=   0.3s
[CV 2/5] END ............model__alpha=0.8;, score=-312620.343 total time=   0.3s
[CV 3/5] END ............model__alpha=0.8;, score=-310323.184 total time=   0.3s
[CV 4/5] END ............model__alpha=0.8;, score=-277101.341 total time=   0.3s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.799e+05, tolerance: 1.208e+05
  model = cd_fast.enet_coordinate_descent(

[CV 5/5] END ............model__alpha=0.8;, score=-311354.791 total time=   0.3s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.013e+06, tolerance: 1.172e+05
  model = cd_fast.enet_coordinate_descent(

[CV 1/5] END ............model__alpha=0.9;, score=-321288.695 total time=   0.3s
[CV 2/5] END ............model__alpha=0.9;, score=-312227.908 total time=   0.3s
[CV 3/5] END ............model__alpha=0.9;, score=-310258.549 total time=   0.3s
[CV 4/5] END ............model__alpha=0.9;, score=-277635.311 total time=   0.3s
[CV 5/5] END ............model__alpha=0.9;, score=-311947.870 total time=   0.3s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.185e+05, tolerance: 1.172e+05
  model = cd_fast.enet_coordinate_descent(

[CV 1/5] END ............model__alpha=1.0;, score=-320446.589 total time=   0.3s
[CV 2/5] END ............model__alpha=1.0;, score=-312206.668 total time=   0.3s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.761e+05, tolerance: 1.189e+05
  model = cd_fast.enet_coordinate_descent(

[CV 3/5] END ............model__alpha=1.0;, score=-310343.339 total time=   0.3s
[CV 4/5] END ............model__alpha=1.0;, score=-278231.314 total time=   0.3s
[CV 5/5] END ............model__alpha=1.0;, score=-312098.070 total time=   0.3s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.353e+05, tolerance: 1.172e+05
  model = cd_fast.enet_coordinate_descent(

[CV 1/5] END ............model__alpha=1.1;, score=-319873.015 total time=   0.3s
[CV 2/5] END ............model__alpha=1.1;, score=-312095.821 total time=   0.3s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.864e+05, tolerance: 1.189e+05
  model = cd_fast.enet_coordinate_descent(

[CV 3/5] END ............model__alpha=1.1;, score=-310456.815 total time=   0.3s
[CV 4/5] END ............model__alpha=1.1;, score=-278795.647 total time=   0.2s
[CV 5/5] END ............model__alpha=1.1;, score=-312074.470 total time=   0.2s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.090e+05, tolerance: 1.172e+05
  model = cd_fast.enet_coordinate_descent(

[CV 1/5] END model__alpha=1.2000000000000002;, score=-319580.773 total time=   0.3s
[CV 2/5] END model__alpha=1.2000000000000002;, score=-311861.832 total time=   0.2s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.780e+05, tolerance: 1.189e+05
  model = cd_fast.enet_coordinate_descent(

[CV 3/5] END model__alpha=1.2000000000000002;, score=-310481.907 total time=   0.3s
[CV 4/5] END model__alpha=1.2000000000000002;, score=-279362.954 total time=   0.2s
[CV 5/5] END model__alpha=1.2000000000000002;, score=-311961.342 total time=   0.3s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.801e+05, tolerance: 1.172e+05
  model = cd_fast.enet_coordinate_descent(

[CV 1/5] END model__alpha=1.3000000000000003;, score=-319340.127 total time=   0.3s
[CV 2/5] END model__alpha=1.3000000000000003;, score=-311548.674 total time=   0.3s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.518e+05, tolerance: 1.189e+05
  model = cd_fast.enet_coordinate_descent(

[CV 3/5] END model__alpha=1.3000000000000003;, score=-310464.182 total time=   0.4s
[CV 4/5] END model__alpha=1.3000000000000003;, score=-279963.310 total time=   0.2s
[CV 5/5] END model__alpha=1.3000000000000003;, score=-311904.051 total time=   0.2s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.118e+05, tolerance: 1.172e+05
  model = cd_fast.enet_coordinate_descent(

[CV 1/5] END model__alpha=1.4000000000000001;, score=-319083.761 total time=   0.3s
[CV 2/5] END model__alpha=1.4000000000000001;, score=-311122.143 total time=   0.2s
[CV 3/5] END model__alpha=1.4000000000000001;, score=-310477.115 total time=   0.3s
[CV 4/5] END model__alpha=1.4000000000000001;, score=-280594.495 total time=   0.2s
[CV 5/5] END model__alpha=1.4000000000000001;, score=-311538.362 total time=   0.2s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.161e+05, tolerance: 1.172e+05
  model = cd_fast.enet_coordinate_descent(

[CV 1/5] END model__alpha=1.5000000000000002;, score=-318817.702 total time=   0.2s
[CV 2/5] END model__alpha=1.5000000000000002;, score=-310746.316 total time=   0.2s
[CV 3/5] END model__alpha=1.5000000000000002;, score=-310325.619 total time=   0.3s
[CV 4/5] END model__alpha=1.5000000000000002;, score=-281113.422 total time=   0.2s
[CV 5/5] END model__alpha=1.5000000000000002;, score=-311009.677 total time=   0.2s

C:\Users\Maninder\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.770e+05, tolerance: 1.172e+05
  model = cd_fast.enet_coordinate_descent(

[CV 1/5] END ............model__alpha=1.6;, score=-318638.988 total time=   0.2s
[CV 2/5] END ............model__alpha=1.6;, score=-310587.864 total time=   0.2s
[CV 3/5] END ............model__alpha=1.6;, score=-310118.148 total time=   0.2s
[CV 4/5] END ............model__alpha=1.6;, score=-281401.160 total time=   0.2s
[CV 5/5] END ............model__alpha=1.6;, score=-310528.310 total time=   0.2s
[CV 1/5] END model__alpha=1.7000000000000002;, score=-318527.358 total time=   0.2s
[CV 2/5] END model__alpha=1.7000000000000002;, score=-310382.690 total time=   0.2s
[CV 3/5] END model__alpha=1.7000000000000002;, score=-310026.116 total time=   0.2s
[CV 4/5] END model__alpha=1.7000000000000002;, score=-281553.396 total time=   0.2s
[CV 5/5] END model__alpha=1.7000000000000002;, score=-310135.474 total time=   0.2s
[CV 1/5] END model__alpha=1.8000000000000003;, score=-318608.215 total time=   0.2s
[CV 2/5] END model__alpha=1.8000000000000003;, score=-310317.898 total time=   0.2s
[CV 3/5] END model__alpha=1.8000000000000003;, score=-309969.149 total time=   0.2s
[CV 4/5] END model__alpha=1.8000000000000003;, score=-281654.640 total time=   0.2s
[CV 5/5] END model__alpha=1.8000000000000003;, score=-309878.432 total time=   0.2s
[CV 1/5] END model__alpha=1.9000000000000001;, score=-318720.887 total time=   0.2s
[CV 2/5] END model__alpha=1.9000000000000001;, score=-310216.299 total time=   0.2s
[CV 3/5] END model__alpha=1.9000000000000001;, score=-309959.033 total time=   0.2s
[CV 4/5] END model__alpha=1.9000000000000001;, score=-281876.295 total time=   0.1s
[CV 5/5] END model__alpha=1.9000000000000001;, score=-309670.845 total time=   0.2s
[CV 1/5] END ............model__alpha=2.0;, score=-318777.202 total time=   0.2s
[CV 2/5] END ............model__alpha=2.0;, score=-310082.831 total time=   0.2s
[CV 3/5] END ............model__alpha=2.0;, score=-309756.584 total time=   0.2s
[CV 4/5] END ............model__alpha=2.0;, score=-282089.696 total time=   0.1s
[CV 5/5] END ............model__alpha=2.0;, score=-309481.731 total time=   0.2s
[CV 1/5] END ............model__alpha=2.1;, score=-318751.316 total time=   0.2s
[CV 2/5] END ............model__alpha=2.1;, score=-309989.407 total time=   0.2s
[CV 3/5] END ............model__alpha=2.1;, score=-309582.792 total time=   0.2s
[CV 4/5] END ............model__alpha=2.1;, score=-282314.449 total time=   0.1s
[CV 5/5] END ............model__alpha=2.1;, score=-309279.789 total time=   0.2s
[CV 1/5] END ............model__alpha=2.2;, score=-318640.909 total time=   0.2s
[CV 2/5] END ............model__alpha=2.2;, score=-309913.763 total time=   0.2s
[CV 3/5] END ............model__alpha=2.2;, score=-309500.640 total time=   0.2s
[CV 4/5] END ............model__alpha=2.2;, score=-282589.616 total time=   0.1s
[CV 5/5] END ............model__alpha=2.2;, score=-308967.770 total time=   0.2s
[CV 1/5] END model__alpha=2.3000000000000003;, score=-318420.012 total time=   0.2s
[CV 2/5] END model__alpha=2.3000000000000003;, score=-309846.927 total time=   0.2s
[CV 3/5] END model__alpha=2.3000000000000003;, score=-309414.691 total time=   0.2s
[CV 4/5] END model__alpha=2.3000000000000003;, score=-282853.493 total time=   0.1s
[CV 5/5] END model__alpha=2.3000000000000003;, score=-308702.274 total time=   0.2s
[CV 1/5] END model__alpha=2.4000000000000004;, score=-318179.439 total time=   0.2s
[CV 2/5] END model__alpha=2.4000000000000004;, score=-309796.446 total time=   0.1s
[CV 3/5] END model__alpha=2.4000000000000004;, score=-309365.409 total time=   0.1s
[CV 4/5] END model__alpha=2.4000000000000004;, score=-283011.087 total time=   0.1s
[CV 5/5] END model__alpha=2.4000000000000004;, score=-308396.275 total time=   0.1s
[CV 1/5] END model__alpha=2.5000000000000004;, score=-317871.906 total time=   0.2s
[CV 2/5] END model__alpha=2.5000000000000004;, score=-309813.148 total time=   0.1s
[CV 3/5] END model__alpha=2.5000000000000004;, score=-309366.158 total time=   0.1s
[CV 4/5] END model__alpha=2.5000000000000004;, score=-283130.395 total time=   0.1s
[CV 5/5] END model__alpha=2.5000000000000004;, score=-308068.395 total time=   0.1s
[CV 1/5] END ............model__alpha=2.6;, score=-317545.216 total time=   0.2s
[CV 2/5] END ............model__alpha=2.6;, score=-309870.938 total time=   0.1s
[CV 3/5] END ............model__alpha=2.6;, score=-309367.626 total time=   0.2s
[CV 4/5] END ............model__alpha=2.6;, score=-283216.059 total time=   0.1s
[CV 5/5] END ............model__alpha=2.6;, score=-307748.926 total time=   0.1s
[CV 1/5] END ............model__alpha=2.7;, score=-317245.893 total time=   0.2s
[CV 2/5] END ............model__alpha=2.7;, score=-309922.883 total time=   0.1s
[CV 3/5] END ............model__alpha=2.7;, score=-309370.425 total time=   0.1s
[CV 4/5] END ............model__alpha=2.7;, score=-283304.321 total time=   0.1s
[CV 5/5] END ............model__alpha=2.7;, score=-307418.486 total time=   0.1s
[CV 1/5] END model__alpha=2.8000000000000003;, score=-316971.719 total time=   0.2s
[CV 2/5] END model__alpha=2.8000000000000003;, score=-309980.785 total time=   0.1s
[CV 3/5] END model__alpha=2.8000000000000003;, score=-309326.771 total time=   0.1s
[CV 4/5] END model__alpha=2.8000000000000003;, score=-283385.907 total time=   0.1s
[CV 5/5] END model__alpha=2.8000000000000003;, score=-307075.401 total time=   0.1s
[CV 1/5] END model__alpha=2.9000000000000004;, score=-316706.201 total time=   0.2s
[CV 2/5] END model__alpha=2.9000000000000004;, score=-309964.408 total time=   0.1s
[CV 3/5] END model__alpha=2.9000000000000004;, score=-309293.057 total time=   0.1s
[CV 4/5] END model__alpha=2.9000000000000004;, score=-283404.078 total time=   0.1s
[CV 5/5] END model__alpha=2.9000000000000004;, score=-306719.249 total time=   0.1s

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model', Lasso())]),
             param_grid={'model__alpha': array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3,
       1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6,
       2.7, 2.8, 2.9])},
             scoring='neg_mean_squared_error', verbose=3)

In [10]:
search.best_params_

{'model__alpha': 2.9000000000000004}

In [85]:
coefficients =search.best_estimator_.named_steps['model'].coef_

In [87]:
importance=np.abs(coefficients)
importance

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.02823452, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.0447151 ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.09623399, 0.        , 0.01085112, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.07053381, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.01504772, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.07061202, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.01297327, 0.        , 0.        ])

In [88]:
[importance>0]

[array([False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False,  True, False, False, False, False, False, False,
        False, False, False, False,  True, False,  True, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False,  True, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False,  True, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False,  True, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False,  True, False, False])]

In [12]:
from sklearn.linear_model import Lasso
 
lasso = Lasso(alpha = [0.05])
lasso.fit(x_train, y_train)
y_pred1 = lasso.predict(x_test)
 
            
lasso_coeff = pd.DataFrame()
lasso_coeff["Columns"] = x_train.columns
lasso_coeff['Coefficient'] = pd.Series(lasso.coef_)
print(lasso_coeff)

InvalidParameterError: The 'alpha' parameter of Lasso must be a float in the range [0, inf). Got [0.05] instead.

In [ ]:
lasso_coeff.to_csv('MRIlasso2.csv', index=True)

In [73]:
lasso_coeff.to_csv('MRIlasso2.csv', index=True)

# Static Features

In [58]:
df=pd.read_csv('C:/Users/Maninder/Desktop/ARIMA.csv')

In [59]:
df=df[df['VISCODE']!='m24']
df

,RID,VISCODE,AGE,PTGENDER,PTEDUCAT,PTETHCAT,PTRACCAT,PTMARRY,APOE4,DX
0,3,bl,81.3,Male,18,Not Hisp/Latino,White,Married,1,AD
1,3,m06,81.3,Male,18,Not Hisp/Latino,White,Married,1,AD
2,3,m12,81.3,Male,18,Not Hisp/Latino,White,Married,1,AD
3,3,m18,81.3,Male,18,Not Hisp/Latino,White,Married,1,AD
5,5,bl,73.7,Male,16,Not Hisp/Latino,White,Married,0,CN
...,...,...,...,...,...,...,...,...,...,...
5698,5004,m18,64.6,Male,20,Not Hisp/Latino,White,Married,0,MCI
5700,5106,bl,74.1,Male,16,Not Hisp/Latino,White,Married,0,AD
5701,5106,m06,74.1,Male,16,Not Hisp/Latino,White,Married,0,AD
5702,5106,m12,74.1,Male,16,Not Hisp/Latino,White,Married,0,AD
5703,5106,m18,74.1,Male,16,Not Hisp/Latino,White,Married,0,AD

In [60]:
df_encoded=pd.get_dummies(df,columns=['PTGENDER','PTETHCAT','PTRACCAT','PTMARRY'])

In [61]:
df_encoded['DX']=df_encoded['DX'].map({'AD':0, 'MCI':1, 'CN':2})

In [62]:
df_encoded

,RID,VISCODE,AGE,PTEDUCAT,APOE4,DX,PTGENDER_Female,PTGENDER_Male,PTETHCAT_Hisp/Latino,PTETHCAT_Not Hisp/Latino,...,PTRACCAT_Black,PTRACCAT_Hawaiian/Other PI,PTRACCAT_More than one,PTRACCAT_Unknown,PTRACCAT_White,PTMARRY_Divorced,PTMARRY_Married,PTMARRY_Never married,PTMARRY_Unknown,PTMARRY_Widowed
0,3,bl,81.3,18,1,0,0,1,0,1,...,0,0,0,0,1,0,1,0,0,0
1,3,m06,81.3,18,1,0,0,1,0,1,...,0,0,0,0,1,0,1,0,0,0
2,3,m12,81.3,18,1,0,0,1,0,1,...,0,0,0,0,1,0,1,0,0,0
3,3,m18,81.3,18,1,0,0,1,0,1,...,0,0,0,0,1,0,1,0,0,0
5,5,bl,73.7,16,0,2,0,1,0,1,...,0,0,0,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5698,5004,m18,64.6,20,0,1,0,1,0,1,...,0,0,0,0,1,0,1,0,0,0
5700,5106,bl,74.1,16,0,0,0,1,0,1,...,0,0,0,0,1,0,1,0,0,0
5701,5106,m06,74.1,16,0,0,0,1,0,1,...,0,0,0,0,1,0,1,0,0,0
5702,5106,m12,74.1,16,0,0,0,1,0,1,...,0,0,0,0,1,0,1,0,0,0
5703,5106,m18,74.1,16,0,0,0,1,0,1,...,0,0,0,0,1,0,1,0,0,0

In [63]:
cols=df_encoded.columns.tolist()
cols.remove('DX')
cols.append('DX')
df_encoded=df_encoded[cols]

In [64]:
df_encoded

,RID,VISCODE,AGE,PTEDUCAT,APOE4,PTGENDER_Female,PTGENDER_Male,PTETHCAT_Hisp/Latino,PTETHCAT_Not Hisp/Latino,PTETHCAT_Unknown,...,PTRACCAT_Hawaiian/Other PI,PTRACCAT_More than one,PTRACCAT_Unknown,PTRACCAT_White,PTMARRY_Divorced,PTMARRY_Married,PTMARRY_Never married,PTMARRY_Unknown,PTMARRY_Widowed,DX
0,3,bl,81.3,18,1,0,1,0,1,0,...,0,0,0,1,0,1,0,0,0,0
1,3,m06,81.3,18,1,0,1,0,1,0,...,0,0,0,1,0,1,0,0,0,0
2,3,m12,81.3,18,1,0,1,0,1,0,...,0,0,0,1,0,1,0,0,0,0
3,3,m18,81.3,18,1,0,1,0,1,0,...,0,0,0,1,0,1,0,0,0,0
5,5,bl,73.7,16,0,0,1,0,1,0,...,0,0,0,1,0,1,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5698,5004,m18,64.6,20,0,0,1,0,1,0,...,0,0,0,1,0,1,0,0,0,1
5700,5106,bl,74.1,16,0,0,1,0,1,0,...,0,0,0,1,0,1,0,0,0,0
5701,5106,m06,74.1,16,0,0,1,0,1,0,...,0,0,0,1,0,1,0,0,0,0
5702,5106,m12,74.1,16,0,0,1,0,1,0,...,0,0,0,1,0,1,0,0,0,0
5703,5106,m18,74.1,16,0,0,1,0,1,0,...,0,0,0,1,0,1,0,0,0,0

In [65]:
import pandas as pd
import numpy as np
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV, train_test_split

In [66]:
#df.fillna(0,inplace=True)
x=df_encoded.iloc[:,2:-1] ## independent features
y=df_encoded.iloc[:,-1] ## dependent features

In [67]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size = 0.30,random_state=42)

In [68]:
x_train

,AGE,PTEDUCAT,APOE4,PTGENDER_Female,PTGENDER_Male,PTETHCAT_Hisp/Latino,PTETHCAT_Not Hisp/Latino,PTETHCAT_Unknown,PTRACCAT_Am Indian/Alaskan,PTRACCAT_Asian,PTRACCAT_Black,PTRACCAT_Hawaiian/Other PI,PTRACCAT_More than one,PTRACCAT_Unknown,PTRACCAT_White,PTMARRY_Divorced,PTMARRY_Married,PTMARRY_Never married,PTMARRY_Unknown,PTMARRY_Widowed
5008,70.7,16,1,1,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0
3315,68.9,14,2,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0
5563,74.2,20,1,0,1,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0
4507,72.0,18,0,0,1,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0
1953,73.4,12,1,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5532,77.1,12,2,0,1,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0
582,78.0,20,0,0,1,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0
3865,66.7,20,1,0,1,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0
4715,64.2,18,0,0,1,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0
1075,86.6,13,1,1,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0

In [69]:
pipeline=Pipeline([
    ('scaler', StandardScaler()),
    ('model', Lasso())              
])

In [70]:
search=GridSearchCV(pipeline,
                  {'model__alpha':np.arange(0.1,3,0.1)},
                   cv=5,
                   scoring='neg_mean_squared_error',
                   verbose=3
                  )

In [71]:
search.fit(x_train,y_train)

Fitting 5 folds for each of 29 candidates, totalling 145 fits
[CV 1/5] END .................model__alpha=0.1;, score=-0.432 total time=   0.0s
[CV 2/5] END .................model__alpha=0.1;, score=-0.441 total time=   0.0s
[CV 3/5] END .................model__alpha=0.1;, score=-0.483 total time=   0.0s
[CV 4/5] END .................model__alpha=0.1;, score=-0.458 total time=   0.0s
[CV 5/5] END .................model__alpha=0.1;, score=-0.468 total time=   0.0s
[CV 1/5] END .................model__alpha=0.2;, score=-0.460 total time=   0.0s
[CV 2/5] END .................model__alpha=0.2;, score=-0.463 total time=   0.0s
[CV 3/5] END .................model__alpha=0.2;, score=-0.518 total time=   0.0s
[CV 4/5] END .................model__alpha=0.2;, score=-0.493 total time=   0.0s
[CV 5/5] END .................model__alpha=0.2;, score=-0.502 total time=   0.0s
[CV 1/5] END .model__alpha=0.30000000000000004;, score=-0.469 total time=   0.0s
[CV 2/5] END .model__alpha=0.30000000000000004;, score=-0.473 total time=   0.0s
[CV 3/5] END .model__alpha=0.30000000000000004;, score=-0.525 total time=   0.0s
[CV 4/5] END .model__alpha=0.30000000000000004;, score=-0.501 total time=   0.0s
[CV 5/5] END .model__alpha=0.30000000000000004;, score=-0.509 total time=   0.0s
[CV 1/5] END .................model__alpha=0.4;, score=-0.469 total time=   0.0s
[CV 2/5] END .................model__alpha=0.4;, score=-0.473 total time=   0.0s
[CV 3/5] END .................model__alpha=0.4;, score=-0.525 total time=   0.0s
[CV 4/5] END .................model__alpha=0.4;, score=-0.501 total time=   0.0s
[CV 5/5] END .................model__alpha=0.4;, score=-0.509 total time=   0.0s
[CV 1/5] END .................model__alpha=0.5;, score=-0.469 total time=   0.0s
[CV 2/5] END .................model__alpha=0.5;, score=-0.473 total time=   0.0s
[CV 3/5] END .................model__alpha=0.5;, score=-0.525 total time=   0.0s
[CV 4/5] END .................model__alpha=0.5;, score=-0.501 total time=   0.0s
[CV 5/5] END .................model__alpha=0.5;, score=-0.509 total time=   0.0s
[CV 1/5] END .................model__alpha=0.6;, score=-0.469 total time=   0.0s
[CV 2/5] END .................model__alpha=0.6;, score=-0.473 total time=   0.0s
[CV 3/5] END .................model__alpha=0.6;, score=-0.525 total time=   0.0s
[CV 4/5] END .................model__alpha=0.6;, score=-0.501 total time=   0.0s
[CV 5/5] END .................model__alpha=0.6;, score=-0.509 total time=   0.0s
[CV 1/5] END ..model__alpha=0.7000000000000001;, score=-0.469 total time=   0.0s
[CV 2/5] END ..model__alpha=0.7000000000000001;, score=-0.473 total time=   0.0s
[CV 3/5] END ..model__alpha=0.7000000000000001;, score=-0.525 total time=   0.0s
[CV 4/5] END ..model__alpha=0.7000000000000001;, score=-0.501 total time=   0.0s
[CV 5/5] END ..model__alpha=0.7000000000000001;, score=-0.509 total time=   0.0s
[CV 1/5] END .................model__alpha=0.8;, score=-0.469 total time=   0.0s
[CV 2/5] END .................model__alpha=0.8;, score=-0.473 total time=   0.0s
[CV 3/5] END .................model__alpha=0.8;, score=-0.525 total time=   0.0s
[CV 4/5] END .................model__alpha=0.8;, score=-0.501 total time=   0.0s
[CV 5/5] END .................model__alpha=0.8;, score=-0.509 total time=   0.0s
[CV 1/5] END .................model__alpha=0.9;, score=-0.469 total time=   0.0s
[CV 2/5] END .................model__alpha=0.9;, score=-0.473 total time=   0.0s
[CV 3/5] END .................model__alpha=0.9;, score=-0.525 total time=   0.0s
[CV 4/5] END .................model__alpha=0.9;, score=-0.501 total time=   0.0s
[CV 5/5] END .................model__alpha=0.9;, score=-0.509 total time=   0.0s
[CV 1/5] END .................model__alpha=1.0;, score=-0.469 total time=   0.0s
[CV 2/5] END .................model__alpha=1.0;, score=-0.473 total time=   0.0s
[CV 3/5] END .................model__alpha=1.0;, score=-0.525 total time=   0.0s
[CV 4/5] END .................model__alpha=1.0;, score=-0.501 total time=   0.0s
[CV 5/5] END .................model__alpha=1.0;, score=-0.509 total time=   0.0s
[CV 1/5] END .................model__alpha=1.1;, score=-0.469 total time=   0.0s
[CV 2/5] END .................model__alpha=1.1;, score=-0.473 total time=   0.0s
[CV 3/5] END .................model__alpha=1.1;, score=-0.525 total time=   0.0s
[CV 4/5] END .................model__alpha=1.1;, score=-0.501 total time=   0.0s
[CV 5/5] END .................model__alpha=1.1;, score=-0.509 total time=   0.0s
[CV 1/5] END ..model__alpha=1.2000000000000002;, score=-0.469 total time=   0.0s
[CV 2/5] END ..model__alpha=1.2000000000000002;, score=-0.473 total time=   0.0s
[CV 3/5] END ..model__alpha=1.2000000000000002;, score=-0.525 total time=   0.0s
[CV 4/5] END ..model__alpha=1.2000000000000002;, score=-0.501 total time=   0.0s
[CV 5/5] END ..model__alpha=1.2000000000000002;, score=-0.509 total time=   0.0s
[CV 1/5] END ..model__alpha=1.3000000000000003;, score=-0.469 total time=   0.0s
[CV 2/5] END ..model__alpha=1.3000000000000003;, score=-0.473 total time=   0.0s
[CV 3/5] END ..model__alpha=1.3000000000000003;, score=-0.525 total time=   0.0s
[CV 4/5] END ..model__alpha=1.3000000000000003;, score=-0.501 total time=   0.0s
[CV 5/5] END ..model__alpha=1.3000000000000003;, score=-0.509 total time=   0.0s
[CV 1/5] END ..model__alpha=1.4000000000000001;, score=-0.469 total time=   0.0s
[CV 2/5] END ..model__alpha=1.4000000000000001;, score=-0.473 total time=   0.0s
[CV 3/5] END ..model__alpha=1.4000000000000001;, score=-0.525 total time=   0.0s
[CV 4/5] END ..model__alpha=1.4000000000000001;, score=-0.501 total time=   0.0s
[CV 5/5] END ..model__alpha=1.4000000000000001;, score=-0.509 total time=   0.0s
[CV 1/5] END ..model__alpha=1.5000000000000002;, score=-0.469 total time=   0.0s
[CV 2/5] END ..model__alpha=1.5000000000000002;, score=-0.473 total time=   0.0s
[CV 3/5] END ..model__alpha=1.5000000000000002;, score=-0.525 total time=   0.0s
[CV 4/5] END ..model__alpha=1.5000000000000002;, score=-0.501 total time=   0.0s
[CV 5/5] END ..model__alpha=1.5000000000000002;, score=-0.509 total time=   0.0s
[CV 1/5] END .................model__alpha=1.6;, score=-0.469 total time=   0.0s
[CV 2/5] END .................model__alpha=1.6;, score=-0.473 total time=   0.0s
[CV 3/5] END .................model__alpha=1.6;, score=-0.525 total time=   0.0s
[CV 4/5] END .................model__alpha=1.6;, score=-0.501 total time=   0.0s
[CV 5/5] END .................model__alpha=1.6;, score=-0.509 total time=   0.0s
[CV 1/5] END ..model__alpha=1.7000000000000002;, score=-0.469 total time=   0.0s
[CV 2/5] END ..model__alpha=1.7000000000000002;, score=-0.473 total time=   0.0s
[CV 3/5] END ..model__alpha=1.7000000000000002;, score=-0.525 total time=   0.0s
[CV 4/5] END ..model__alpha=1.7000000000000002;, score=-0.501 total time=   0.0s
[CV 5/5] END ..model__alpha=1.7000000000000002;, score=-0.509 total time=   0.0s
[CV 1/5] END ..model__alpha=1.8000000000000003;, score=-0.469 total time=   0.0s
[CV 2/5] END ..model__alpha=1.8000000000000003;, score=-0.473 total time=   0.0s
[CV 3/5] END ..model__alpha=1.8000000000000003;, score=-0.525 total time=   0.0s
[CV 4/5] END ..model__alpha=1.8000000000000003;, score=-0.501 total time=   0.0s
[CV 5/5] END ..model__alpha=1.8000000000000003;, score=-0.509 total time=   0.0s
[CV 1/5] END ..model__alpha=1.9000000000000001;, score=-0.469 total time=   0.0s
[CV 2/5] END ..model__alpha=1.9000000000000001;, score=-0.473 total time=   0.0s
[CV 3/5] END ..model__alpha=1.9000000000000001;, score=-0.525 total time=   0.0s
[CV 4/5] END ..model__alpha=1.9000000000000001;, score=-0.501 total time=   0.0s
[CV 5/5] END ..model__alpha=1.9000000000000001;, score=-0.509 total time=   0.0s
[CV 1/5] END .................model__alpha=2.0;, score=-0.469 total time=   0.0s
[CV 2/5] END .................model__alpha=2.0;, score=-0.473 total time=   0.0s
[CV 3/5] END .................model__alpha=2.0;, score=-0.525 total time=   0.0s
[CV 4/5] END .................model__alpha=2.0;, score=-0.501 total time=   0.0s
[CV 5/5] END .................model__alpha=2.0;, score=-0.509 total time=   0.0s
[CV 1/5] END .................model__alpha=2.1;, score=-0.469 total time=   0.0s
[CV 2/5] END .................model__alpha=2.1;, score=-0.473 total time=   0.0s
[CV 3/5] END .................model__alpha=2.1;, score=-0.525 total time=   0.0s
[CV 4/5] END .................model__alpha=2.1;, score=-0.501 total time=   0.0s
[CV 5/5] END .................model__alpha=2.1;, score=-0.509 total time=   0.0s
[CV 1/5] END .................model__alpha=2.2;, score=-0.469 total time=   0.0s
[CV 2/5] END .................model__alpha=2.2;, score=-0.473 total time=   0.0s
[CV 3/5] END .................model__alpha=2.2;, score=-0.525 total time=   0.0s
[CV 4/5] END .................model__alpha=2.2;, score=-0.501 total time=   0.0s
[CV 5/5] END .................model__alpha=2.2;, score=-0.509 total time=   0.0s
[CV 1/5] END ..model__alpha=2.3000000000000003;, score=-0.469 total time=   0.0s
[CV 2/5] END ..model__alpha=2.3000000000000003;, score=-0.473 total time=   0.0s
[CV 3/5] END ..model__alpha=2.3000000000000003;, score=-0.525 total time=   0.0s
[CV 4/5] END ..model__alpha=2.3000000000000003;, score=-0.501 total time=   0.0s
[CV 5/5] END ..model__alpha=2.3000000000000003;, score=-0.509 total time=   0.0s
[CV 1/5] END ..model__alpha=2.4000000000000004;, score=-0.469 total time=   0.0s
[CV 2/5] END ..model__alpha=2.4000000000000004;, score=-0.473 total time=   0.0s
[CV 3/5] END ..model__alpha=2.4000000000000004;, score=-0.525 total time=   0.0s
[CV 4/5] END ..model__alpha=2.4000000000000004;, score=-0.501 total time=   0.0s
[CV 5/5] END ..model__alpha=2.4000000000000004;, score=-0.509 total time=   0.0s
[CV 1/5] END ..model__alpha=2.5000000000000004;, score=-0.469 total time=   0.0s
[CV 2/5] END ..model__alpha=2.5000000000000004;, score=-0.473 total time=   0.0s
[CV 3/5] END ..model__alpha=2.5000000000000004;, score=-0.525 total time=   0.0s
[CV 4/5] END ..model__alpha=2.5000000000000004;, score=-0.501 total time=   0.0s
[CV 5/5] END ..model__alpha=2.5000000000000004;, score=-0.509 total time=   0.0s
[CV 1/5] END .................model__alpha=2.6;, score=-0.469 total time=   0.0s
[CV 2/5] END .................model__alpha=2.6;, score=-0.473 total time=   0.0s
[CV 3/5] END .................model__alpha=2.6;, score=-0.525 total time=   0.0s
[CV 4/5] END .................model__alpha=2.6;, score=-0.501 total time=   0.0s
[CV 5/5] END .................model__alpha=2.6;, score=-0.509 total time=   0.0s
[CV 1/5] END .................model__alpha=2.7;, score=-0.469 total time=   0.0s
[CV 2/5] END .................model__alpha=2.7;, score=-0.473 total time=   0.0s
[CV 3/5] END .................model__alpha=2.7;, score=-0.525 total time=   0.0s
[CV 4/5] END .................model__alpha=2.7;, score=-0.501 total time=   0.0s
[CV 5/5] END .................model__alpha=2.7;, score=-0.509 total time=   0.0s
[CV 1/5] END ..model__alpha=2.8000000000000003;, score=-0.469 total time=   0.0s
[CV 2/5] END ..model__alpha=2.8000000000000003;, score=-0.473 total time=   0.0s
[CV 3/5] END ..model__alpha=2.8000000000000003;, score=-0.525 total time=   0.0s
[CV 4/5] END ..model__alpha=2.8000000000000003;, score=-0.501 total time=   0.0s
[CV 5/5] END ..model__alpha=2.8000000000000003;, score=-0.509 total time=   0.0s
[CV 1/5] END ..model__alpha=2.9000000000000004;, score=-0.469 total time=   0.0s
[CV 2/5] END ..model__alpha=2.9000000000000004;, score=-0.473 total time=   0.0s
[CV 3/5] END ..model__alpha=2.9000000000000004;, score=-0.525 total time=   0.0s
[CV 4/5] END ..model__alpha=2.9000000000000004;, score=-0.501 total time=   0.0s
[CV 5/5] END ..model__alpha=2.9000000000000004;, score=-0.509 total time=   0.0s

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model', Lasso())]),
             param_grid={'model__alpha': array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3,
       1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6,
       2.7, 2.8, 2.9])},
             scoring='neg_mean_squared_error', verbose=3)

In [72]:
search.best_params_

{'model__alpha': 0.1}

In [73]:
from sklearn.linear_model import Lasso
 
lasso = Lasso(alpha = [0.03])
lasso.fit(x_train, y_train)
y_pred1 = lasso.predict(x_test)
 
            
lasso_coeff = pd.DataFrame()
lasso_coeff["Columns"] = x_train.columns
lasso_coeff['Coefficient'] = pd.Series(lasso.coef_)
print(lasso_coeff)
lasso_

InvalidParameterError: The 'alpha' parameter of Lasso must be a float in the range [0, inf). Got [0.03] instead.

In [ ]:
import matplotlib.pyplot as plt

# Create a dataframe to store the coefficients
lasso_coeff = pd.DataFrame()
lasso_coeff["Feature"] = x_train.columns
lasso_coeff["Coefficient"] = lasso.coef_

# Sort the coefficients by their absolute values
lasso_coeff = lasso_coeff.reindex(lasso_coeff["Coefficient"].abs().sort_values(ascending=False).index)

# Create a bar plot to show the relative importance of each feature
plt.figure(figsize=(10, 8))
plt.barh(y=lasso_coeff["Feature"], width=lasso_coeff["Coefficient"])
plt.xlabel("Coefficient")
plt.ylabel("Feature")
plt.title("Lasso Feature Importance")
plt.show()

In [57]:
lasso_coeff.to_csv('Demolasso.csv', index=True)

In [90]:
df=pd.read_csv('C:/Users/student/5 visits.csv')

In [91]:
df_encoded=pd.get_dummies(df,columns=['PTGENDER','PTETHCAT','PTRACCAT','PTMARRY'])

In [92]:
df_encoded['DX']=df_encoded['DX'].map({'AD':0, 'MCI':1, 'CN':2})

In [93]:
cols=df_encoded.columns.tolist()
cols.remove('DX')
cols.append('DX')
df_encoded=df_encoded[cols]

In [94]:
df_encoded

,RID,VISCODE,AGE,PTEDUCAT,APOE4,CDRSB,ADAS11,ADAS13,MMSE,RAVLT_immediate,...,PTRACCAT_Hawaiian/Other PI,PTRACCAT_More than one,PTRACCAT_Unknown,PTRACCAT_White,PTMARRY_Divorced,PTMARRY_Married,PTMARRY_Never married,PTMARRY_Unknown,PTMARRY_Widowed,DX
0,3,bl,81.3,18,1,4.5,22.00,31.00,20,22.0,...,0,0,0,1,0,1,0,0,0,0
1,3,m06,81.3,18,1,6.0,19.00,30.00,24,19.0,...,0,0,0,1,0,1,0,0,0,0
2,3,m12,81.3,18,1,3.5,24.00,35.00,17,31.0,...,0,0,0,1,0,1,0,0,0,0
3,3,m18,81.3,18,1,3.5,24.00,35.00,17,31.0,...,0,0,0,1,0,1,0,0,0,0
4,3,m24,81.3,18,1,8.0,25.67,37.67,19,23.0,...,0,0,0,1,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5700,5106,bl,74.1,16,0,4.0,30.00,42.00,20,18.0,...,0,0,0,1,0,1,0,0,0,0
5701,5106,m06,74.1,16,0,6.0,26.00,38.00,17,12.0,...,0,0,0,1,0,1,0,0,0,0
5702,5106,m12,74.1,16,0,6.0,26.00,38.00,17,12.0,...,0,0,0,1,0,1,0,0,0,0
5703,5106,m18,74.1,16,0,6.0,26.00,38.00,17,12.0,...,0,0,0,1,0,1,0,0,0,0
5704,5106,m24,74.1,16,0,6.0,26.00,38.00,17,12.0,...,0,0,0,1,0,1,0,0,0,0

In [95]:
import pandas as pd
import numpy as np
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV, train_test_split

In [96]:
#df.fillna(0,inplace=True)
x=df_encoded.iloc[:,2:-1] ## independent features
y=df_encoded.iloc[:,-1] ## dependent features

In [97]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size = 0.30,random_state=42)

In [98]:
pipeline=Pipeline([
    ('scaler', StandardScaler()),
    ('model', Lasso())              
])

In [99]:
search=GridSearchCV(pipeline,
                  {'model__alpha':np.arange(0.1,10,0.1)},
                   cv=5,
                   scoring='neg_mean_squared_error',
                   verbose=3
                  )

In [100]:
search.fit(x_train,y_train)

Fitting 5 folds for each of 99 candidates, totalling 495 fits
[CV 1/5] END .................model__alpha=0.1;, score=-0.209 total time=   0.0s
[CV 2/5] END .................model__alpha=0.1;, score=-0.193 total time=   0.0s
[CV 3/5] END .................model__alpha=0.1;, score=-0.191 total time=   0.0s
[CV 4/5] END .................model__alpha=0.1;, score=-0.202 total time=   0.0s
[CV 5/5] END .................model__alpha=0.1;, score=-0.185 total time=   0.0s
[CV 1/5] END .................model__alpha=0.2;, score=-0.257 total time=   0.0s
[CV 2/5] END .................model__alpha=0.2;, score=-0.232 total time=   0.0s
[CV 3/5] END .................model__alpha=0.2;, score=-0.235 total time=   0.0s
[CV 4/5] END .................model__alpha=0.2;, score=-0.241 total time=   0.0s
[CV 5/5] END .................model__alpha=0.2;, score=-0.227 total time=   0.0s
[CV 1/5] END .model__alpha=0.30000000000000004;, score=-0.319 total time=   0.0s
[CV 2/5] END .model__alpha=0.30000000000000004;, score=-0.293 total time=   0.0s
[CV 3/5] END .model__alpha=0.30000000000000004;, score=-0.298 total time=   0.0s
[CV 4/5] END .model__alpha=0.30000000000000004;, score=-0.296 total time=   0.0s
[CV 5/5] END .model__alpha=0.30000000000000004;, score=-0.281 total time=   0.0s
[CV 1/5] END .................model__alpha=0.4;, score=-0.398 total time=   0.0s
[CV 2/5] END .................model__alpha=0.4;, score=-0.375 total time=   0.0s
[CV 3/5] END .................model__alpha=0.4;, score=-0.378 total time=   0.0s
[CV 4/5] END .................model__alpha=0.4;, score=-0.370 total time=   0.0s
[CV 5/5] END .................model__alpha=0.4;, score=-0.354 total time=   0.0s
[CV 1/5] END .................model__alpha=0.5;, score=-0.489 total time=   0.0s
[CV 2/5] END .................model__alpha=0.5;, score=-0.475 total time=   0.0s
[CV 3/5] END .................model__alpha=0.5;, score=-0.468 total time=   0.0s
[CV 4/5] END .................model__alpha=0.5;, score=-0.458 total time=   0.0s
[CV 5/5] END .................model__alpha=0.5;, score=-0.439 total time=   0.0s
[CV 1/5] END .................model__alpha=0.6;, score=-0.541 total time=   0.0s
[CV 2/5] END .................model__alpha=0.6;, score=-0.538 total time=   0.0s
[CV 3/5] END .................model__alpha=0.6;, score=-0.524 total time=   0.0s
[CV 4/5] END .................model__alpha=0.6;, score=-0.518 total time=   0.0s
[CV 5/5] END .................model__alpha=0.6;, score=-0.496 total time=   0.0s
[CV 1/5] END ..model__alpha=0.7000000000000001;, score=-0.541 total time=   0.0s
[CV 2/5] END ..model__alpha=0.7000000000000001;, score=-0.538 total time=   0.0s
[CV 3/5] END ..model__alpha=0.7000000000000001;, score=-0.524 total time=   0.0s
[CV 4/5] END ..model__alpha=0.7000000000000001;, score=-0.518 total time=   0.0s
[CV 5/5] END ..model__alpha=0.7000000000000001;, score=-0.496 total time=   0.0s
[CV 1/5] END .................model__alpha=0.8;, score=-0.541 total time=   0.0s
[CV 2/5] END .................model__alpha=0.8;, score=-0.538 total time=   0.0s
[CV 3/5] END .................model__alpha=0.8;, score=-0.524 total time=   0.0s
[CV 4/5] END .................model__alpha=0.8;, score=-0.518 total time=   0.0s
[CV 5/5] END .................model__alpha=0.8;, score=-0.496 total time=   0.0s
[CV 1/5] END .................model__alpha=0.9;, score=-0.541 total time=   0.0s
[CV 2/5] END .................model__alpha=0.9;, score=-0.538 total time=   0.0s
[CV 3/5] END .................model__alpha=0.9;, score=-0.524 total time=   0.0s
[CV 4/5] END .................model__alpha=0.9;, score=-0.518 total time=   0.0s
[CV 5/5] END .................model__alpha=0.9;, score=-0.496 total time=   0.0s
[CV 1/5] END .................model__alpha=1.0;, score=-0.541 total time=   0.0s
[CV 2/5] END .................model__alpha=1.0;, score=-0.538 total time=   0.0s
[CV 3/5] END .................model__alpha=1.0;, score=-0.524 total time=   0.0s
[CV 4/5] END .................model__alpha=1.0;, score=-0.518 total time=   0.0s
[CV 5/5] END .................model__alpha=1.0;, score=-0.496 total time=   0.0s
[CV 1/5] END .................model__alpha=1.1;, score=-0.541 total time=   0.0s
[CV 2/5] END .................model__alpha=1.1;, score=-0.538 total time=   0.0s
[CV 3/5] END .................model__alpha=1.1;, score=-0.524 total time=   0.0s
[CV 4/5] END .................model__alpha=1.1;, score=-0.518 total time=   0.0s
[CV 5/5] END .................model__alpha=1.1;, score=-0.496 total time=   0.0s
[CV 1/5] END ..model__alpha=1.2000000000000002;, score=-0.541 total time=   0.0s
[CV 2/5] END ..model__alpha=1.2000000000000002;, score=-0.538 total time=   0.0s
[CV 3/5] END ..model__alpha=1.2000000000000002;, score=-0.524 total time=   0.0s
[CV 4/5] END ..model__alpha=1.2000000000000002;, score=-0.518 total time=   0.0s
[CV 5/5] END ..model__alpha=1.2000000000000002;, score=-0.496 total time=   0.0s
[CV 1/5] END ..model__alpha=1.3000000000000003;, score=-0.541 total time=   0.0s
[CV 2/5] END ..model__alpha=1.3000000000000003;, score=-0.538 total time=   0.0s
[CV 3/5] END ..model__alpha=1.3000000000000003;, score=-0.524 total time=   0.0s
[CV 4/5] END ..model__alpha=1.3000000000000003;, score=-0.518 total time=   0.0s
[CV 5/5] END ..model__alpha=1.3000000000000003;, score=-0.496 total time=   0.0s
[CV 1/5] END ..model__alpha=1.4000000000000001;, score=-0.541 total time=   0.0s
[CV 2/5] END ..model__alpha=1.4000000000000001;, score=-0.538 total time=   0.0s
[CV 3/5] END ..model__alpha=1.4000000000000001;, score=-0.524 total time=   0.0s
[CV 4/5] END ..model__alpha=1.4000000000000001;, score=-0.518 total time=   0.0s
[CV 5/5] END ..model__alpha=1.4000000000000001;, score=-0.496 total time=   0.0s
[CV 1/5] END ..model__alpha=1.5000000000000002;, score=-0.541 total time=   0.0s
[CV 2/5] END ..model__alpha=1.5000000000000002;, score=-0.538 total time=   0.0s
[CV 3/5] END ..model__alpha=1.5000000000000002;, score=-0.524 total time=   0.0s
[CV 4/5] END ..model__alpha=1.5000000000000002;, score=-0.518 total time=   0.0s
[CV 5/5] END ..model__alpha=1.5000000000000002;, score=-0.496 total time=   0.0s
[CV 1/5] END .................model__alpha=1.6;, score=-0.541 total time=   0.0s
[CV 2/5] END .................model__alpha=1.6;, score=-0.538 total time=   0.0s
[CV 3/5] END .................model__alpha=1.6;, score=-0.524 total time=   0.0s
[CV 4/5] END .................model__alpha=1.6;, score=-0.518 total time=   0.0s
[CV 5/5] END .................model__alpha=1.6;, score=-0.496 total time=   0.0s
[CV 1/5] END ..model__alpha=1.7000000000000002;, score=-0.541 total time=   0.0s
[CV 2/5] END ..model__alpha=1.7000000000000002;, score=-0.538 total time=   0.0s
[CV 3/5] END ..model__alpha=1.7000000000000002;, score=-0.524 total time=   0.0s
[CV 4/5] END ..model__alpha=1.7000000000000002;, score=-0.518 total time=   0.0s
[CV 5/5] END ..model__alpha=1.7000000000000002;, score=-0.496 total time=   0.0s
[CV 1/5] END ..model__alpha=1.8000000000000003;, score=-0.541 total time=   0.0s
[CV 2/5] END ..model__alpha=1.8000000000000003;, score=-0.538 total time=   0.0s
[CV 3/5] END ..model__alpha=1.8000000000000003;, score=-0.524 total time=   0.0s
[CV 4/5] END ..model__alpha=1.8000000000000003;, score=-0.518 total time=   0.0s
[CV 5/5] END ..model__alpha=1.8000000000000003;, score=-0.496 total time=   0.0s
[CV 1/5] END ..model__alpha=1.9000000000000001;, score=-0.541 total time=   0.0s
[CV 2/5] END ..model__alpha=1.9000000000000001;, score=-0.538 total time=   0.0s
[CV 3/5] END ..model__alpha=1.9000000000000001;, score=-0.524 total time=   0.0s
[CV 4/5] END ..model__alpha=1.9000000000000001;, score=-0.518 total time=   0.0s
[CV 5/5] END ..model__alpha=1.9000000000000001;, score=-0.496 total time=   0.0s
[CV 1/5] END .................model__alpha=2.0;, score=-0.541 total time=   0.0s
[CV 2/5] END .................model__alpha=2.0;, score=-0.538 total time=   0.0s
[CV 3/5] END .................model__alpha=2.0;, score=-0.524 total time=   0.0s
[CV 4/5] END .................model__alpha=2.0;, score=-0.518 total time=   0.0s
[CV 5/5] END .................model__alpha=2.0;, score=-0.496 total time=   0.0s
[CV 1/5] END .................model__alpha=2.1;, score=-0.541 total time=   0.0s
[CV 2/5] END .................model__alpha=2.1;, score=-0.538 total time=   0.0s
[CV 3/5] END .................model__alpha=2.1;, score=-0.524 total time=   0.0s
[CV 4/5] END .................model__alpha=2.1;, score=-0.518 total time=   0.0s
[CV 5/5] END .................model__alpha=2.1;, score=-0.496 total time=   0.0s
[CV 1/5] END .................model__alpha=2.2;, score=-0.541 total time=   0.0s
[CV 2/5] END .................model__alpha=2.2;, score=-0.538 total time=   0.0s
[CV 3/5] END .................model__alpha=2.2;, score=-0.524 total time=   0.0s
[CV 4/5] END .................model__alpha=2.2;, score=-0.518 total time=   0.0s
[CV 5/5] END .................model__alpha=2.2;, score=-0.496 total time=   0.0s
[CV 1/5] END ..model__alpha=2.3000000000000003;, score=-0.541 total time=   0.0s
[CV 2/5] END ..model__alpha=2.3000000000000003;, score=-0.538 total time=   0.0s
[CV 3/5] END ..model__alpha=2.3000000000000003;, score=-0.524 total time=   0.0s
[CV 4/5] END ..model__alpha=2.3000000000000003;, score=-0.518 total time=   0.0s
[CV 5/5] END ..model__alpha=2.3000000000000003;, score=-0.496 total time=   0.0s
[CV 1/5] END ..model__alpha=2.4000000000000004;, score=-0.541 total time=   0.0s
[CV 2/5] END ..model__alpha=2.4000000000000004;, score=-0.538 total time=   0.0s
[CV 3/5] END ..model__alpha=2.4000000000000004;, score=-0.524 total time=   0.0s
[CV 4/5] END ..model__alpha=2.4000000000000004;, score=-0.518 total time=   0.0s
[CV 5/5] END ..model__alpha=2.4000000000000004;, score=-0.496 total time=   0.0s
[CV 1/5] END ..model__alpha=2.5000000000000004;, score=-0.541 total time=   0.0s
[CV 2/5] END ..model__alpha=2.5000000000000004;, score=-0.538 total time=   0.0s
[CV 3/5] END ..model__alpha=2.5000000000000004;, score=-0.524 total time=   0.0s
[CV 4/5] END ..model__alpha=2.5000000000000004;, score=-0.518 total time=   0.0s
[CV 5/5] END ..model__alpha=2.5000000000000004;, score=-0.496 total time=   0.0s
[CV 1/5] END .................model__alpha=2.6;, score=-0.541 total time=   0.0s
[CV 2/5] END .................model__alpha=2.6;, score=-0.538 total time=   0.0s
[CV 3/5] END .................model__alpha=2.6;, score=-0.524 total time=   0.0s
[CV 4/5] END .................model__alpha=2.6;, score=-0.518 total time=   0.0s
[CV 5/5] END .................model__alpha=2.6;, score=-0.496 total time=   0.0s
[CV 1/5] END .................model__alpha=2.7;, score=-0.541 total time=   0.0s
[CV 2/5] END .................model__alpha=2.7;, score=-0.538 total time=   0.0s
[CV 3/5] END .................model__alpha=2.7;, score=-0.524 total time=   0.0s
[CV 4/5] END .................model__alpha=2.7;, score=-0.518 total time=   0.0s
[CV 5/5] END .................model__alpha=2.7;, score=-0.496 total time=   0.0s
[CV 1/5] END ..model__alpha=2.8000000000000003;, score=-0.541 total time=   0.0s
[CV 2/5] END ..model__alpha=2.8000000000000003;, score=-0.538 total time=   0.0s
[CV 3/5] END ..model__alpha=2.8000000000000003;, score=-0.524 total time=   0.0s
[CV 4/5] END ..model__alpha=2.8000000000000003;, score=-0.518 total time=   0.0s
[CV 5/5] END ..model__alpha=2.8000000000000003;, score=-0.496 total time=   0.0s
[CV 1/5] END ..model__alpha=2.9000000000000004;, score=-0.541 total time=   0.0s
[CV 2/5] END ..model__alpha=2.9000000000000004;, score=-0.538 total time=   0.0s
[CV 3/5] END ..model__alpha=2.9000000000000004;, score=-0.524 total time=   0.0s
[CV 4/5] END ..model__alpha=2.9000000000000004;, score=-0.518 total time=   0.0s
[CV 5/5] END ..model__alpha=2.9000000000000004;, score=-0.496 total time=   0.0s
[CV 1/5] END ..model__alpha=3.0000000000000004;, score=-0.541 total time=   0.0s
[CV 2/5] END ..model__alpha=3.0000000000000004;, score=-0.538 total time=   0.0s
[CV 3/5] END ..model__alpha=3.0000000000000004;, score=-0.524 total time=   0.0s
[CV 4/5] END ..model__alpha=3.0000000000000004;, score=-0.518 total time=   0.0s
[CV 5/5] END ..model__alpha=3.0000000000000004;, score=-0.496 total time=   0.0s
[CV 1/5] END .................model__alpha=3.1;, score=-0.541 total time=   0.0s
[CV 2/5] END .................model__alpha=3.1;, score=-0.538 total time=   0.0s
[CV 3/5] END .................model__alpha=3.1;, score=-0.524 total time=   0.0s
[CV 4/5] END .................model__alpha=3.1;, score=-0.518 total time=   0.0s
[CV 5/5] END .................model__alpha=3.1;, score=-0.496 total time=   0.0s
[CV 1/5] END .................model__alpha=3.2;, score=-0.541 total time=   0.0s
[CV 2/5] END .................model__alpha=3.2;, score=-0.538 total time=   0.0s
[CV 3/5] END .................model__alpha=3.2;, score=-0.524 total time=   0.0s
[CV 4/5] END .................model__alpha=3.2;, score=-0.518 total time=   0.0s
[CV 5/5] END .................model__alpha=3.2;, score=-0.496 total time=   0.0s
[CV 1/5] END ..model__alpha=3.3000000000000003;, score=-0.541 total time=   0.0s
[CV 2/5] END ..model__alpha=3.3000000000000003;, score=-0.538 total time=   0.0s
[CV 3/5] END ..model__alpha=3.3000000000000003;, score=-0.524 total time=   0.0s
[CV 4/5] END ..model__alpha=3.3000000000000003;, score=-0.518 total time=   0.0s
[CV 5/5] END ..model__alpha=3.3000000000000003;, score=-0.496 total time=   0.0s
[CV 1/5] END ..model__alpha=3.4000000000000004;, score=-0.541 total time=   0.0s
[CV 2/5] END ..model__alpha=3.4000000000000004;, score=-0.538 total time=   0.0s
[CV 3/5] END ..model__alpha=3.4000000000000004;, score=-0.524 total time=   0.0s
[CV 4/5] END ..model__alpha=3.4000000000000004;, score=-0.518 total time=   0.0s
[CV 5/5] END ..model__alpha=3.4000000000000004;, score=-0.496 total time=   0.0s
[CV 1/5] END ..model__alpha=3.5000000000000004;, score=-0.541 total time=   0.0s
[CV 2/5] END ..model__alpha=3.5000000000000004;, score=-0.538 total time=   0.0s
[CV 3/5] END ..model__alpha=3.5000000000000004;, score=-0.524 total time=   0.0s
[CV 4/5] END ..model__alpha=3.5000000000000004;, score=-0.518 total time=   0.0s
[CV 5/5] END ..model__alpha=3.5000000000000004;, score=-0.496 total time=   0.0s
[CV 1/5] END .................model__alpha=3.6;, score=-0.541 total time=   0.0s
[CV 2/5] END .................model__alpha=3.6;, score=-0.538 total time=   0.0s
[CV 3/5] END .................model__alpha=3.6;, score=-0.524 total time=   0.0s
[CV 4/5] END .................model__alpha=3.6;, score=-0.518 total time=   0.0s
[CV 5/5] END .................model__alpha=3.6;, score=-0.496 total time=   0.0s
[CV 1/5] END .................model__alpha=3.7;, score=-0.541 total time=   0.0s
[CV 2/5] END .................model__alpha=3.7;, score=-0.538 total time=   0.0s
[CV 3/5] END .................model__alpha=3.7;, score=-0.524 total time=   0.0s
[CV 4/5] END .................model__alpha=3.7;, score=-0.518 total time=   0.0s
[CV 5/5] END .................model__alpha=3.7;, score=-0.496 total time=   0.0s
[CV 1/5] END ..model__alpha=3.8000000000000003;, score=-0.541 total time=   0.0s
[CV 2/5] END ..model__alpha=3.8000000000000003;, score=-0.538 total time=   0.0s
[CV 3/5] END ..model__alpha=3.8000000000000003;, score=-0.524 total time=   0.0s
[CV 4/5] END ..model__alpha=3.8000000000000003;, score=-0.518 total time=   0.0s
[CV 5/5] END ..model__alpha=3.8000000000000003;, score=-0.496 total time=   0.0s
[CV 1/5] END ..model__alpha=3.9000000000000004;, score=-0.541 total time=   0.0s
[CV 2/5] END ..model__alpha=3.9000000000000004;, score=-0.538 total time=   0.0s
[CV 3/5] END ..model__alpha=3.9000000000000004;, score=-0.524 total time=   0.0s
[CV 4/5] END ..model__alpha=3.9000000000000004;, score=-0.518 total time=   0.0s
[CV 5/5] END ..model__alpha=3.9000000000000004;, score=-0.496 total time=   0.0s
[CV 1/5] END .................model__alpha=4.0;, score=-0.541 total time=   0.0s
[CV 2/5] END .................model__alpha=4.0;, score=-0.538 total time=   0.0s
[CV 3/5] END .................model__alpha=4.0;, score=-0.524 total time=   0.0s
[CV 4/5] END .................model__alpha=4.0;, score=-0.518 total time=   0.0s
[CV 5/5] END .................model__alpha=4.0;, score=-0.496 total time=   0.0s
[CV 1/5] END .................model__alpha=4.1;, score=-0.541 total time=   0.0s
[CV 2/5] END .................model__alpha=4.1;, score=-0.538 total time=   0.0s
[CV 3/5] END .................model__alpha=4.1;, score=-0.524 total time=   0.0s
[CV 4/5] END .................model__alpha=4.1;, score=-0.518 total time=   0.0s
[CV 5/5] END .................model__alpha=4.1;, score=-0.496 total time=   0.0s
[CV 1/5] END .................model__alpha=4.2;, score=-0.541 total time=   0.0s
[CV 2/5] END .................model__alpha=4.2;, score=-0.538 total time=   0.0s
[CV 3/5] END .................model__alpha=4.2;, score=-0.524 total time=   0.0s
[CV 4/5] END .................model__alpha=4.2;, score=-0.518 total time=   0.0s
[CV 5/5] END .................model__alpha=4.2;, score=-0.496 total time=   0.0s
[CV 1/5] END .................model__alpha=4.3;, score=-0.541 total time=   0.0s
[CV 2/5] END .................model__alpha=4.3;, score=-0.538 total time=   0.0s
[CV 3/5] END .................model__alpha=4.3;, score=-0.524 total time=   0.0s
[CV 4/5] END .................model__alpha=4.3;, score=-0.518 total time=   0.0s
[CV 5/5] END .................model__alpha=4.3;, score=-0.496 total time=   0.0s
[CV 1/5] END ..model__alpha=4.3999999999999995;, score=-0.541 total time=   0.0s
[CV 2/5] END ..model__alpha=4.3999999999999995;, score=-0.538 total time=   0.0s
[CV 3/5] END ..model__alpha=4.3999999999999995;, score=-0.524 total time=   0.0s
[CV 4/5] END ..model__alpha=4.3999999999999995;, score=-0.518 total time=   0.0s
[CV 5/5] END ..model__alpha=4.3999999999999995;, score=-0.496 total time=   0.0s
[CV 1/5] END .................model__alpha=4.5;, score=-0.541 total time=   0.0s
[CV 2/5] END .................model__alpha=4.5;, score=-0.538 total time=   0.0s
[CV 3/5] END .................model__alpha=4.5;, score=-0.524 total time=   0.0s
[CV 4/5] END .................model__alpha=4.5;, score=-0.518 total time=   0.0s
[CV 5/5] END .................model__alpha=4.5;, score=-0.496 total time=   0.0s
[CV 1/5] END .................model__alpha=4.6;, score=-0.541 total time=   0.0s
[CV 2/5] END .................model__alpha=4.6;, score=-0.538 total time=   0.0s
[CV 3/5] END .................model__alpha=4.6;, score=-0.524 total time=   0.0s
[CV 4/5] END .................model__alpha=4.6;, score=-0.518 total time=   0.0s
[CV 5/5] END .................model__alpha=4.6;, score=-0.496 total time=   0.0s
[CV 1/5] END .................model__alpha=4.7;, score=-0.541 total time=   0.0s
[CV 2/5] END .................model__alpha=4.7;, score=-0.538 total time=   0.0s
[CV 3/5] END .................model__alpha=4.7;, score=-0.524 total time=   0.0s
[CV 4/5] END .................model__alpha=4.7;, score=-0.518 total time=   0.0s
[CV 5/5] END .................model__alpha=4.7;, score=-0.496 total time=   0.0s
[CV 1/5] END .................model__alpha=4.8;, score=-0.541 total time=   0.0s
[CV 2/5] END .................model__alpha=4.8;, score=-0.538 total time=   0.0s
[CV 3/5] END .................model__alpha=4.8;, score=-0.524 total time=   0.0s
[CV 4/5] END .................model__alpha=4.8;, score=-0.518 total time=   0.0s
[CV 5/5] END .................model__alpha=4.8;, score=-0.496 total time=   0.0s
[CV 1/5] END .................model__alpha=4.9;, score=-0.541 total time=   0.0s
[CV 2/5] END .................model__alpha=4.9;, score=-0.538 total time=   0.0s
[CV 3/5] END .................model__alpha=4.9;, score=-0.524 total time=   0.0s
[CV 4/5] END .................model__alpha=4.9;, score=-0.518 total time=   0.0s
[CV 5/5] END .................model__alpha=4.9;, score=-0.496 total time=   0.0s
[CV 1/5] END .................model__alpha=5.0;, score=-0.541 total time=   0.0s

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model', Lasso())]),
             param_grid={'model__alpha': array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3,
       1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6,
       2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9,
       4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2,
       5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5,
       6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8,
       7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. , 9.1,
       9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])},
             scoring='neg_mean_squared_error', verbose=3)

In [101]:
search.best_params_

{'model__alpha': 0.1}

In [102]:
from sklearn.linear_model import Lasso
 
lasso = Lasso(alpha = [0.03])
lasso.fit(x_train, y_train)
y_pred1 = lasso.predict(x_test)
 
            
lasso_coeff = pd.DataFrame()
lasso_coeff["Columns"] = x_train.columns
lasso_coeff['Coefficient'] = pd.Series(lasso.coef_)
print(lasso_coeff)

                   Columns  Coefficient
0                      AGE     0.010597
1                 PTEDUCAT     0.000650
2                    APOE4    -0.000000
3                    CDRSB    -0.095676
4                   ADAS11     0.014814
..                     ...          ...
370       PTMARRY_Divorced     0.000000
371        PTMARRY_Married    -0.000000
372  PTMARRY_Never married     0.000000
373        PTMARRY_Unknown    -0.000000
374        PTMARRY_Widowed    -0.000000

[375 rows x 2 columns]

C:\Users\student\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.109e+01, tolerance: 2.088e-01
  model = cd_fast.enet_coordinate_descent(

In [103]:
lasso_coeff.to_csv('allfusedlasso.csv', index=True)

In [94]:
from sklearn.linear_model import Lasso
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

df = pd.read_csv('C:/Users/Maninder/Desktop/ARIMA.csv')
df=df[df['VISCODE']!='m24']
df
#df_encoded = pd.get_dummies(df,columns=['PTGENDER','PTETHCAT','PTRACCAT','PTMARRY'])
df['DX'] = df['DX'].map({'AD':0, 'MCI':1, 'CN':2})

In [95]:
x = df.iloc[:,2:-1] # independent features
y = df.iloc[:,-1] # dependent feature

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=42)

In [96]:
y_train

5008    0
3315    1
5563    1
4507    1
1953    2
       ..
5532    1
582     2
3865    0
4715    1
1075    0
Name: DX, Length: 3194, dtype: int64

In [97]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [98]:
lasso = Lasso(alpha=0.015)
lasso.fit(x_train_scaled, y_train)
y_pred1 = lasso.predict(x_test_scaled)

In [99]:
lasso_coeff = pd.DataFrame()
lasso_coeff["Columns"] = x_train.columns
lasso_coeff['Coefficient'] = pd.Series(lasso.coef_)
print(lasso_coeff)

                                         Columns  Coefficient
0    ST101SV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16     0.000000
1    ST102CV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16    -0.018763
2    ST102SA_UCSFFSX_11_02_15_UCSFFSX51_08_01_16    -0.000000
3    ST102TA_UCSFFSX_11_02_15_UCSFFSX51_08_01_16    -0.000000
4    ST102TS_UCSFFSX_11_02_15_UCSFFSX51_08_01_16    -0.000000
..                                           ...          ...
323   ST99CV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16     0.000000
324   ST99SA_UCSFFSX_11_02_15_UCSFFSX51_08_01_16    -0.000000
325   ST99TA_UCSFFSX_11_02_15_UCSFFSX51_08_01_16     0.025870
326   ST99TS_UCSFFSX_11_02_15_UCSFFSX51_08_01_16    -0.000000
327    ST9SV_UCSFFSX_11_02_15_UCSFFSX51_08_01_16     0.000406

[328 rows x 2 columns]

In [100]:
lasso_coeff.to_csv('Demolasso1.csv', index=True)